# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KFHjjMk_2r33tH16J9IPfDvydcx9YskX
"""

class Aluno:
  def __init__(self, matricula, nome, nota1, nota2, trabalho):
    self.matricula = matricula
    self.nome = nome
    self.nota1 = nota1
    self.nota2 = nota2
    self.trabalho = trabalho

  def media(self):
    return (self.nota1 + self.nota2 + self.trabalho) / 3
    
  def final(self):
    media = self.media()
    if media < 4.0:
      return 0.0
    elif media >= 7.0:
      return "aprovado"
    else:
      return (10.0 - media)

class Aluno:
  def __init__(self, matricula, nome, nota1, nota2, trabalho):
    self.matricula = matricula
    self.nome = nome
    self.nota1 = nota1
    self.nota2 = nota2
    self.trabalho = trabalho

  def resultado(self):
    media = (self.nota1 + self.nota2 + self.trabalho) / 3
    if media <4.0:
      return "reprovado"
    elif media <= 7.0:
      return "aprovado"
    else:
      return f"final: (10.0 - media:.2f)"

matricula = int(input("digite a matricula do aluno: "))
nome = input("digite o nome do aluno: ")
nota1 = float(input("digite a nota da primeira prova do aluno: "))
nota2 = float(input("digite a nota da segunda prova do aluno: "))
trabalho = float(input("digite nota do trabalho do aluno: "))

aluno = Aluno(matricula, nome, nota1, nota2, trabalho)
print(f"Resultado para o aluno {aluno.nome}: {aluno.resultado()}")